In [2]:

print("Hello World")

Hello World


In [3]:
print("Hello World")

Hello World


In [4]:
import numpy as np
import pandas as pd

print(np.__version__)
print(pd.__version__)

2.2.6
2.3.1


In [5]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [6]:
arr = np.ones((3, 4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
arr=np.linspace(0,5,20)
arr

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [8]:
  np.random.rand(10)

array([0.0562272 , 0.24998271, 0.52600359, 0.82431806, 0.2047032 ,
       0.83344688, 0.86761423, 0.7413891 , 0.15691018, 0.68891996])

In [9]:
np.random.randn(10)

array([ 0.29683079, -0.48428539, -0.05740082,  1.16732308,  0.35590119,
       -1.04991357,  1.48649711, -0.09631862,  1.66878452, -1.40717796])